name = input("who are you?")
city = input("where do you live?")
age = input("how old are you?")
hobby = input("what is your hobby?")
movie = input("what is your favourite movie?")
food = input("what is your favourite food?")

print("-----------print your details filled by you----------")
print("Name:", name)
print("City:", city)
print("Age:", age)
print("Hobby:", hobby)
print("movie:", movie)
print("Food:", food)
print ("-----------The End------")